### ISSUE TITLE
Default runtime in Windows?

### ISSUE THREAD

**Issue by memsharded** [calebkiage/conan-cmake-toolchain#1]
Hi @calebkiage 

I am having a first look at this project, and so far I am liking it, I am a bit surprised that the CMake toolchain will let us go that far, but seems to work fine, good job.

I wonder about:
```cmake
# Set runtime type based on BUILD_SHARED_LIBS value
        if (BUILD_SHARED_LIBS)
            set(conan_install_args "${conan_install_args};--settings:host;compiler.runtime=dynamic")
        else()
            set(conan_install_args "${conan_install_args};--settings:host;compiler.runtime=static")
        endif()
```
I am not sure that building a static library means you should be linking with the MSVC static runtime. In general the dynamic one is always preferred, for all types of libraries, static and shared. I think it would make sense to change it or am I missing something?

**Comment by calebkiage** [comment]
Hey @memsharded, yeah. I was testing out the impact of that flag. If we change this, it means that the toolchain file can remove that section of code completely and users can just set the runtime in the profile. I'll update that.

**Comment by calebkiage** [comment]
I've updated it. Thanks for the tip. I like that it reduces the cmake code :-)

**Comment by memsharded** [comment]
Great!
Closing this issue, we will keep investigating this, as we said, not high priority because we are swamped with 2.0, but this is looking promising!
