### ISSUE TITLE
Link to Similiar Projects

### ISSUE THREAD

**Issue by heilkn** [calebkiage/conan-cmake-toolchain#2]
Hi!

I started this doscussion a few weeks ago 
https://github.com/conan-io/conan/issues/12341
and created this prototype https://github.com/heilkn/conan-toolchain

Are intetested you intetested to collaborate on this?

Kind regards

Konstantin

**Comment by calebkiage** [comment]
Hey @heilkn, sure. I started this to use conan in my personal projects. If you think it would be useful for your applications too, I'm happy to work together on it :-)

**Comment by heilkn** [comment]
I am glad you are interested. Could you please provide a LICENSE for your code? I chose MIT for my prototype, because it is the license used for the conan client itself and my goal would be to get this integrated upstream.

**Comment by calebkiage** [comment]
License has been added.
